name: Missing Data
description: File a missing data report
title: 'missing: '
labels: [type/other, status/triage]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this report!
  - type: textarea
    id: what-is-missing
    attributes:
      label: What's missing?
      description: A clear and concise description of what data is missing.
      placeholder: This is what is missing...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce?
      description: A list of steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See that ___ is missing
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Links? Screenshots? References? Any additional context?
      placeholder: Here's some extra info...
  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting...
      options:
        - label: This issue is not a duplicate of an existing issue (open or closed).
          required: true
